name: bytechat
description: "Um protótipo de chat em tempo real com Flutter, Supabase e Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Essencial para o Supabase
  supabase_flutter: ^2.5.0

  # Essencial para o Firebase (Core e Messaging para futuras notificações)
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
