name: bytechat
description: "Um aplicativo de chat em tempo real construído com Flutter e Supabase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências do Firebase que já tínhamos
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2

  # NOVAS DEPENDÊNCIAS ADICIONADAS CONFORME O ERRO
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  intl: ^0.19.0 # Pacote para formatação de datas
  
  # O Supabase não está sendo usado neste novo código, mas podemos deixar aqui por enquanto.
  supabase_flutter: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
